Various fixes

diff --git a/octave/octave.SlackBuild b/octave/octave.SlackBuild
--- a/octave/octave.SlackBuild
+++ b/octave/octave.SlackBuild
@@ -44,6 +44,8 @@ if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
 fi
 DOCS="AUTHORS BUGS CITATION COPYING ChangeLog INSTALL* NEWS README"
 
+export CXXFLAGS="-std=gnu++17"
+
 if [ "$ARCH" = "i586" ]; then
   SLKCFLAGS="-O2 -march=i586 -mtune=i686"
   LIBDIRSUFFIX=""
@@ -86,8 +88,126 @@ fi
 
 if ! [[ -f /usr/lib/liblapack.so ]]; then
 	echo "LAPACK is not installed. You need it to compile GNU Octave."
+	exit
 fi
-wget -c https://ftpmirror.gnu.org/gnu/$PRGNAM/$PRGNAM-$VERSION.tar.lz
+
+if ! [[ -f /usr/lib/libarpack.so ]]; then
+	echo "ARPACK is not installed. You need it to compile GNU Octave."
+	exit
+fi
+
+if ! [[ -f /opt/qt6/lib/libQt6Core.so ]]; then
+	echo "Qt6 is not installed. You need it to compile GNU Octave with a GUI."
+	exit
+fi
+
+if ! [[ -f /opt/qt6/lib/libqscintilla2_qt6.so ]]; then
+	echo "QScintilla with Qt6 support is not installed. You need it to compile GNU Octave with a GUI."
+fi
+
+if ! [[ -f /usr/lib/libhdf5.so ]]; then
+	echo "HDF5 is not installed. It is required to compile GNU Octave."
+	exit
+fi
+
+if ! [[ -f /usr/lib/libfftw3.so ]]; then
+	echo "FFTW is not installed. It is required to compile GNU Octave."
+	exit
+fi
+
+if ! [[ -f /usr/lib/libGraphicsMagick.so ]]; then
+	echo "GraphicsMagick is not installed. It is required to compile GNU Octave."
+	exit
+fi
+
+if ! [[ -f /usr/lib/libglpk.so ]]; then
+	echo "GLPK is not installed and is required to compile GNU Octave."
+	exit
+fi
+
+if ! [[ -f /usr/lib/libcurl.so ]]; then
+	echo "cURL is not installed. It is required to install GNU Octave."
+	exit
+fi
+
+if ! [[ -f /usr/lib/libqhull.so ]]; then
+	echo "QHull is not installed and it is required to compile GNU Octave."
+	exit
+fi
+
+if ! [[ -f /usr/lib/libGLU.so ]]; then
+	echo "GLU is not installed and it is required to compile GNU Octave."
+	exit
+fi
+
+if ! [[ -d /usr/share/ghostscript ]]; then
+	echo "Ghostscript isn't installed and it is required to compile GNU Octave."
+	exit
+fi
+
+if ! [[ -f /usr/lib/libsundials_core.so ]]; then
+	echo "Sundials isn't installed and it is required to compile GNU Octave."
+	exit
+fi
+
+if ! [[ -f /usr/lib/libgl2ps.so ]]; then
+	echo "gl2ps isn't installed and it is required to compile GNU Octave."
+	exit
+fi
+
+if ! [[ -f /usr/lib/libsndfile.so ]]; then
+	echo "libsndfile isn't installed and is required to compile GNU Octave."
+	exit
+fi
+
+if ! [[ -f /usr/lib/libqrupdate.so ]]; then
+	echo "Qrupdate isn't installed and is required to compile GNU Octave."
+	exit
+fi
+
+if ! [[ -f /usr/bin/pcre2-config ]]; then
+	echo "pcre2 isn't installed and is required to compile GNU Octave."
+	exit
+fi
+
+if ! which gfortran &> /dev/null; then
+	echo "gfortran is not found within PATH. It is required to compile GNU Octave and its dependencies like LAPACK."
+	exit
+fi
+
+if ! [[ -f /usr/lib/libsuitesparse_mongoose.so ]]; then
+	echo "suitesparse isn't installed and is required to comple GNU Octave."
+	exit
+fi
+
+if ! which info &> /dev/null; then
+	echo "texinfo isn't installed and is required to compile GNU Octave."
+	exit
+fi
+
+if ! which gnuplot &> /dev/null ; then
+	echo "Gnuplot isn't installed and it is required for some plotting in Octave."
+fi
+
+if ! which fltk &> /dev/null; then
+	echo "FLTK is required by some features for GNU Octave."
+fi
+
+if ! [[ -f /usr/lib/libportaudio.so ]]; then
+	echo "PortAudio isn't installed and is required for audio support in GNU Octave."
+fi
+
+if ! [[ -f /usr/include/rapidjson/prettywriter.h ]]; then
+	echo "RapidJSON isn't installed and is required for JSON support in Octave."
+fi
+
+if ! [[ -d /opt/OpenJDK-21.0.9-bin/bin ]]; then
+	echo "Java not found. It is required to build GNU Octave."
+	exit
+fi
+if ! [[ -f $PRGNAM-$VERSION.tar.lz ]]; then
+	wget -c https://ftpmirror.gnu.org/gnu/$PRGNAM/$PRGNAM-$VERSION.tar.lz
+fi
 rm -rf $PRGNAM-$VERSION
 tar xvf $CWD/$PRGNAM-$VERSION.tar.lz
 cd $PRGNAM-$VERSION
@@ -101,6 +221,11 @@ autoreconf -vif
 # timezone, then the docs get rebuilt with your local date.
 find . -name stamp-vti -exec touch {} +
 
+export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/qt6/lib
+export PATH=$PATH:/opt/qt6/bin
+export JAVA_HOME=/opt/OpenJDK-21.0.9-bin
+export CPPFLAGS="-I/usr/include"
+export PKG_CONFIG_PATH=/opt/qt6/lib/pkgconfig:$PKG_CONFIG_PATH
 ./configure \
   --prefix=/usr \
   --libdir=\${exec_prefix}/lib${LIBDIRSUFFIX} \
@@ -113,9 +238,8 @@ find . -name stamp-vti -exec touch {} +
   --with-openssl=auto \
   ${MAGICK} \
   CFLAGS="$SLKCFLAGS" \
-  CXXFLAGS="$SLKCFLAGS" \
-  FFLAGS="$SLKCFLAGS" \
-
+  CXXFLAGS="$SLKCFLAGS -std=gnu++17" \
+  FFLAGS="$SLKCFLAGS"
   make -j$(nproc)
 # TODO: May fail if not all optional deps are installed (gl2ps in particular).
 #make check
@@ -123,3 +247,5 @@ sudo make install-strip DESTDIR=/
 
 sudo mkdir -p /usr/share/doc/$PRGNAM-$VERSION
 sudo cp -a $DOCS /usr/share/doc/$PRGNAM-$VERSION
+sudo install -dm755 $CWD/octave_exec /usr/bin/
+sudo sed -i -e "s|/usr/bin/octave|/usr/bin/octave_cli|g" /usr/share/applications/org.octave.Octave.desktop
